sudo: required

language: ruby

services:
         - docker

before_install:
         - docker-compose up -d
         - sudo /etc/init.d/postgresql stop

install:
        - gem update bundler
        - bundle install

script:
      - bundle exec rspec spec/tests/
