version: '3'
services:
  db:
    image: postgres
  server:
    build: .
    volumes:
      - .:/palladium
    ports:
      - "80:80"
    command: ["puma"]
    environment:
      - JWT_SECRET=abc
      - JWT_ISSUER=abc
      - RACK_ENV=test
    depends_on:
      - db
