:production:
  adapter: postgres
  database: postgres
  username: postgres
  host: db
  max_connections: 50

:development:
  adapter: postgres
  database: pall5
  username: postgres
  host: localhost
  max_connections: 50

:test:
  adapter: postgres
  database: postgres
  password: password
  username: postgres
  host: db
  max_connections: 50
